# Generated by Django 5.2.1 on 2025-05-10 15:05

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioMedia',
            fields=[
                ('id', models.UUIDField(default=core.models.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=191, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('source', models.CharField(blank=True, help_text='Where the audio came from', max_length=191, verbose_name='Source')),
                ('subtitle', models.CharField(blank=True, help_text='A short subtitle summarizing the content (30-150 chars)', max_length=191, verbose_name='Subtitle')),
                ('is_private', models.BooleanField(default=False, help_text='If enabled, only authenticated users can view this media', verbose_name='Private')),
                ('original_file', models.FileField(upload_to='media/original/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'mp4', 'aac', 'wav', 'm4a', 'flac'])], verbose_name='Original File')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='media/processed/%Y/%m/%d/', verbose_name='Processed AAC File')),
                ('processing_date', models.DateTimeField(blank=True, null=True, verbose_name='Processing Date')),
                ('processing_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20, verbose_name='Processing Status')),
                ('transcription_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20, verbose_name='Transcription Status')),
                ('transcription_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Transcription Start Date')),
                ('transcription_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Transcription End Date')),
                ('raw_transcription', models.JSONField(blank=True, null=True, verbose_name='Raw Transcription')),
                ('formatted_transcription', models.TextField(blank=True, verbose_name='Formatted Transcription')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('summary_type', models.CharField(default='GENERAL', max_length=20, verbose_name='Summary Type')),
                ('summary_date', models.DateTimeField(blank=True, null=True, verbose_name='Summary Date')),
                ('selected_model', models.CharField(blank=True, max_length=50, verbose_name='Selected LLM Model')),
            ],
            options={
                'verbose_name': 'Audio Media',
                'verbose_name_plural': 'Audio Media',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='SummarySnapshot',
            fields=[
                ('id', models.UUIDField(default=core.models.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('summary_type', models.CharField(max_length=20, verbose_name='Summary Type')),
                ('summary', models.TextField(verbose_name='Summary Content')),
                ('llm_provider', models.CharField(max_length=20, verbose_name='LLM Provider')),
                ('llm_model', models.CharField(max_length=50, verbose_name='LLM Model')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Raw LLM Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('audio_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_snapshots', to='core.audiomedia')),
            ],
            options={
                'verbose_name': 'Summary Snapshot',
                'verbose_name_plural': 'Summary Snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
