# Generated by Django 5.2.1 on 2025-05-08 14:57

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=191, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('original_file', models.FileField(upload_to='media/original/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'mp4', 'aac', 'wav', 'm4a', 'flac'])], verbose_name='Original File')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='media/processed/%Y/%m/%d/', verbose_name='Processed AAC File')),
                ('processing_date', models.DateTimeField(blank=True, null=True, verbose_name='Processing Date')),
                ('processing_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20, verbose_name='Processing Status')),
                ('transcription_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20, verbose_name='Transcription Status')),
                ('transcription_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Transcription Start Date')),
                ('transcription_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Transcription End Date')),
                ('raw_transcription', models.JSONField(blank=True, null=True, verbose_name='Raw Transcription')),
                ('formatted_transcription', models.TextField(blank=True, verbose_name='Formatted Transcription')),
            ],
            options={
                'verbose_name': 'Audio Media',
                'verbose_name_plural': 'Audio Media',
                'ordering': ['-upload_date'],
            },
        ),
    ]
