# Generated by Django 5.2.1 on 2025-05-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomedia',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='audiomedia',
            name='summary_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Summary Date'),
        ),
        migrations.AddField(
            model_name='audiomedia',
            name='summary_type',
            field=models.CharField(default='GENERAL', max_length=20, verbose_name='Summary Type'),
        ),
    ]
