# Generated by Django 5.2.1 on 2025-05-09 06:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audiomedia_summary_audiomedia_summary_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomedia',
            name='selected_model',
            field=models.CharField(blank=True, max_length=50, verbose_name='Selected LLM Model'),
        ),
        migrations.CreateModel(
            name='SummarySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_type', models.CharField(max_length=20, verbose_name='Summary Type')),
                ('summary', models.TextField(verbose_name='Summary Content')),
                ('llm_provider', models.CharField(max_length=20, verbose_name='LLM Provider')),
                ('llm_model', models.CharField(max_length=50, verbose_name='LLM Model')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Raw LLM Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('audio_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_snapshots', to='core.audiomedia')),
            ],
            options={
                'verbose_name': 'Summary Snapshot',
                'verbose_name_plural': 'Summary Snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
