# Generated by Django 5.2.1 on 2025-05-10 04:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_audiomedia_selected_model_summarysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomedia',
            name='source',
            field=models.CharField(blank=True, help_text='Where the audio came from', max_length=255, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='audiomedia',
            name='subtitle',
            field=models.CharField(blank=True, help_text='A short subtitle summarizing the content (30-150 chars)', max_length=150, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='audiomedia',
            name='id',
            field=models.UUIDField(default=core.models.get_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='summarysnapshot',
            name='id',
            field=models.UUIDField(default=core.models.get_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
