# Generated by Django 5.2.1 on 2025-05-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_audiomedia_source_audiomedia_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomedia',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If enabled, only authenticated users can view this media', verbose_name='Private'),
        ),
    ]
