version: '3.8'

services:
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ../static:/app/static
      - ../media:/app/media
    depends_on:
      - web
    restart: always

  web:
    image: aweffr/streamsparkai:latest
    volumes:
      - ../static:/app/static
      - ../media:/app/media
      - ../logs:/app/logs
      - ../tmp:/app/tmp
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL:-mysql://user:password@db:3306/streamsparkai}
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      # Superuser credentials, only will automatically create if no users exist
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      # Storage configuration
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # API keys
      - ALIBABA_DASHSCOPE_API_KEY=${ALIBABA_DASHSCOPE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE:-https://api.openai.com/v1}
      - DEFAULT_OPENAI_MODEL=${DEFAULT_OPENAI_MODEL:-gemini-2.5-flash-preview-04-17}
      - ALIBABA_LLM_MODEL=${ALIBABA_LLM_MODEL:-qwen-max}
      - DEFAULT_LLM_PROVIDER=${DEFAULT_LLM_PROVIDER:-openai}
    restart: always
    command: sleep inf

  db:
    image: mysql:8.0
    volumes:
      - spark_mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-streamsparkai}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  spark_mysql_data:
